swagger: '2.0'
info: 
  title: 'QUANTUM-ZZ API'
  description: 'The API is an HTTP interface for working with ZZ data. The base path for all API requests is https://api.zz.com/v1/. Use  https://sandbox-api.zz.com/v1/ - for testing purpozes.'
  version: 1.0.1
schemes:
  - https
  - http
host: 'api.zz.com'
basePath: '/v1'
consumes:
  - application/json
produces:
  - application/json
paths:
  /order/get:
    get:
      summary: 'Get an existing shipping order'
      description: 'Этот метод используется для получения данных заказа. Ответ возвращается в виде объекта ShippingOrder'
      operationId: getOrder
      parameters:
        - name: orderId
          in: query
          description: 'ID of shipping order to return'
          required: true
          type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/ShippingOrder'
        400:
          description: 'invalid ID supplied'
        404:
          description: 'shippingOrder not found'
  /order/list:
    get:
      summary: 'Get shipping order list by update_date'
      description: 'Этот метод используется для получения списка заказов данные которых были изменены после указанной даты. Ответ возвращается в виде массива ShippingOrder'
      operationId: getOrderList
      parameters:
        - name: update_date
          in: query
          description: 'Date to filter objects'
          required: false
          type: string
        - name: page
          in: query
          required: false
          description: 'Pagination'
          type: integer
        - name: limit
          in: query
          required: false
          description: 'Limits the number of ids to be retrieved. Values between 1—100 are accepted. Defaults to 100.'
          type: integer
        - name: filter
          in: query
          required: false
          description: 'Additional filter (to be discussed with ZZ) ???'
          type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            type: array
            items:
              $ref: '#/definitions/ShippingOrder'
        404:
          description: 'ShippingOrders not found'
  /client/get:
    get:
      summary: 'Get an existing client'
      description: 'Этот метод используется для получения данных клиента. Ответ возвращается в виде объекта Client'
      operationId: getClient
      parameters:
        - name: clientId
          in: query
          description: 'ID of client to return'
          required: true
          type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/Client'
        400:
          description: 'invalid ID supplied'
        404:
          description: 'client not found'
  /client/list:
    get:
      summary: 'Get client list by update_date'
      description: 'Этот метод используется для получения списка клиентов данные которых были изменены после указанной даты. Ответ возвращается в виде массива объектов Client.'
      operationId: getClientList
      parameters:
        - name: update_date
          in: query
          description: 'Date to filter objects'
          required: false
          type: string
        - name: page
          in: query
          required: false
          description: 'Pagination'
          type: integer
        - name: limit
          in: query
          required: false
          description: 'Limits the number of ids to be retrieved. Values between 1—100 are accepted. Defaults to 100.'
          type: integer
        - name: filter
          in: query
          required: false
          description: 'Additional filter (to be discussed with ZZ) ???'
          type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            type: array
            items:
              $ref: '#/definitions/Client'
        404:
          description: 'clients not found'
  /contractstatus/set:
    put:
      summary: 'Method is used to set contract status and link'
      operationId: setContractStatus
      description: 'Этот метод используется для передачи статуса подписания договора и ссылки на PDF/Вчасно для просмотра. Ссылка на просмотр PDF договора и его статус будут отображаться в кабинете клиента ZZ Не изменяет update_date'
      parameters:
        - name: clientId
          in: query
          description: 'client id (ZZ)'
          required: true
          type: string
        - name: contract_status
          in: query
          description: 'Contract status'
          required: false
          type: string
          items:
            enum:
              - signed
              - refused
              - waiting
        - name: link
          in: query
          description: 'Link to PDF/Vchasno'
          required: false
          type: string
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
        405:
          description: 'validation exception'
  /clientcheckstatus/set:
    put:
      summary: 'Method is used to set client check status'
      operationId: setClientCheckStatus
      description: 'Этот метод используется для передачи статуса проверки клиента (например средствами U-Control). Статусы проверки клиента будут отображаться в кабинете клиента ZZ. Не изменяет update_date'
      parameters:
        - name: clientId
          in: query
          description: 'client id (ZZ)'
          required: true
          type: string
        - name: check_status
          in: query
          description: 'Check status'
          required: true
          type: string
          items:
            enum:
              - passed
              - failed
        - name: check_type
          in: query
          description: 'Type of check'
          required: true
          type: string
          items:
            enum:
              - ucontrol
              - internal
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
  /clientpaymentcondition/set:
    put:
      summary: 'Method is used to set client payment condition'
      operationId: setClientPaymentCondition
      description: 'Этот метод используется для установки порядка оплаты клиенту. Порядок оплаты клиента будет отображаться в кабинете клиента ZZ. Не изменяет update_date'
      parameters:
        - name: clientId
          in: query
          description: 'client id (ZZ)'
          required: true
          type: string
        - name: payment_condition
          in: query
          description: 'condition in contract (prepayment/deferment of payment __days)'
          required: true
          type: string
          items:
            enum:
              - prepayment
              - deferment of payment __days
              - etc
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
  /documentcheckstatus/set:
    put:
      summary: 'Method is used to set document check status'
      operationId: setDocumentCheckStatus
      description: 'Этот метод используется для передачи статуса проверки документа. Статус проверки документа будет отображаться в кабинете клиента ZZ. Не изменяет update_date'
      parameters:
        - name: documentId
          in: query
          description: 'document id (ZZ)'
          required: true
          type: string
        - name: check_status
          in: query
          description: 'Check status'
          required: true
          type: string
          items:
            enum:
              - passed
              - failed
        - name: rejection_reason
          in: query
          description: 'required if "status is denied" - reason of denied status'
          required: false
          type: string
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
  /signeddocumentsignstatus/set:
    put:
      summary: 'Method is used to set status of signed document and link'
      operationId: setSignedDocumentSignStatus
      description: 'Этот метод используется для передачи данных статуса подписи и ссылок на PDF/Вчасно документа заказа. Ссылки на просмотр PDF документов будут отображаться в ShippingOrder ZZ. Не изменяет update_date'
      parameters:
        - name: signedDocumentId
          in: query
          description: 'signed document id (ZZ)'
          required: true
          type: string
        - name: sign_status
          in: query
          description: 'Check status'
          required: true
          type: string
          items:
            enum:
              - signed
              - rejected
              - waiting
        - name: link
          in: query
          type: string
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
  /orderpayment/set:
    put:
      summary: 'Method is used to set order payment'
      operationId: setOrderPayment
      description: 'Этот метод используется для установки суммы оплаты заказа. Не изменяет update_date'
      parameters:
        - name: orderId
          in: query
          description: 'order id (ZZ)'
          required: true
          type: string
        - name: payment_sum
          in: query
          description: 'Check status'
          required: true
          type: number
      responses:
        200:
          description: 'successful operation'
        400:
          description: 'invalid ID supplied'
        405:
          description: 'validation exception'
definitions:
  ShippingOrder:
    type: object
    properties:
      id:
        type: string
        description: 'Origin: ZZ'
      update_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      deleted:
        type: boolean
        default: false
        description: 'Origin: ZZ'
      date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      shipment_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      unload_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      transport_owner:
        $ref: '#/definitions/Client'
      contact_person_to:
        $ref: '#/definitions/ContactPerson'
      cargo_owner:
          $ref: '#/definitions/Client'
      contact_person_co:
          $ref: '#/definitions/ContactPerson'
      consignee:
          $ref: '#/definitions/Client'
      contact_person_consignee:
          $ref: '#/definitions/ContactPerson'
      currency:
        description: 'Origin: ZZ'
        type: string
      sum_co:
        type: number
        example: 293.25
        description: 'Origin: ZZ'
      sum_to:
        type: number
        example: 765.43
        description: 'Origin: ZZ'
      loading_address:
        type: string
        description: 'Origin: ZZ'
      unloading_address:
        type: string
        description: 'Origin: ZZ'
      comment:
        type: string
        description: 'Origin: ZZ'
      vehicle:
        $ref: '#/definitions/Vehicle'
      driver:
        $ref: '#/definitions/Person'
      payment_sum:
        type: number
        example: 1024.32
        description: 'Origin: ZZ'
      signed_documents:
        description: 'Origin: 1C'
        type: array
        items:
          $ref: '#/definitions/SignedDocument'
      execution_status:
        type: string
        description: 'Origin: ZZ'
        enum:
          - order_created
          - order_canceled
          - tender
          - tender_confirmation
          - waiting_truck
          - waiting_loading
          - loading
          - on_the_way
          - waiting_unloading
          - unloading
          - delivered
  ClientCheckInfo:
    type: object
    properties:
      check_type:
        description: 'Origin: 1C'
        type: string
        enum:
          - ucontrol
          - internal
      check_status:
        description: 'Origin: 1C'
        type: string
        enum:
          - passed
          - failed
  Client:
    type: object
    properties:
      id:
        type: string
        description: 'Origin: ZZ'
      update_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      deleted:
        type: boolean
        default: false
        description: 'Origin: ZZ'
      full_name:
        type: string
        description: 'Origin: ZZ. Full company name'
      responsible_person:
        type: string
        description: 'Origin: ZZ. Official person can sign legal docs'
      responsible_person_position:
        type: string
        description: 'Origin: ZZ'
      responsibility_document:
        $ref: '#/definitions/Document'
      responsibility_document_validity:
        description: 'Origin: ZZ.	Validity of responsibility document'
        type: string
        format: date-time
      payment_condition:
        type: string
        enum:
          - fullprepayment
          - deferment_of_payment_days
        description: 'Origin:ZZ. condition in contract (prepayment/deferment of payment __days)'
      comment:
        description: 'Origin: ZZ'
        type: string
      registration_number:
        description: 'Origin: ZZ'
        type: string
      vat_number:
        description: 'Origin: ZZ'
        type: string
      type_of_client:
        description: 'Origin: ZZ'
        type: string
        enum:
          - legal
          - individual
          - private_enterpreneur
      legal_address:
        description: 'Origin: ZZ'
        type: string
      correspondence_address:
        description: 'Origin: ZZ'
        type: string
      contact_details:
        $ref: '#/definitions/ContactData'
      registration:
        $ref: '#/definitions/Document'
      poa:
        $ref: '#/definitions/Document'
      charter:
        $ref: '#/definitions/Document'
      certificate:
        $ref: '#/definitions/Document'
      passport:
        $ref: '#/definitions/Document'
      id_code:
        $ref: '#/definitions/Document'
      type_of_activity:
        description: 'Origin: ZZ'
        type: string
        enum:
          - co
          - to
      bank_account:
        $ref: '#/definitions/BankAccount'
      contact_person:
        $ref: '#/definitions/ContactPerson'
      signed_documents:
        description: 'Origin: 1C'
        type: array
        items:
          $ref: '#/definitions/SignedDocument'
      contract_status:
        description: 'Origin: 1C'
        type: string
        enum:
          - signed
          - refused
          - waiting
      check_info:
        description: 'Origin: 1C'
        type: array
        items:
          $ref: '#/definitions/ClientCheckInfo'
  ContactPerson:
    type: object
    properties:
      name:
        type: string
        description: 'Origin: ZZ'
      comment:
        type: string
        description: 'Origin: ZZ'
      contact_data:
        $ref: '#/definitions/ContactData'
  Vehicle:
    type: object
    properties:
      model:          
        type: string
        description: 'Origin: ZZ'
      car_number:          
        type: string
        description: 'Origin: ZZ'
      trailer_number:          
        type: string
        description: 'Origin: ZZ'
  Person:
    type: object
    properties:
      name:
        type: string
        description: 'Origin: ZZ'
      type:
        description: 'Origin: ZZ'
        type: string
        enum:
          - passport
          - drivers_licese
          - etc
      documents:
        description: 'Origin: ZZ'
        type: array
        items:
          $ref: '#/definitions/Document'
      birth_date:
        description: 'Origin: ZZ'
        type: string
        format: date-time
      gender:
        description: 'Origin: ZZ'
        type: string
        enum:
          - male
          - female
          - etc
      nationality:
        description: 'Origin: ZZ'
        type: string
      contact_data:
        $ref: '#/definitions/ContactData'
  Document:
    type: object
    properties:
      id:
        description: 'Origin: ZZ'
        type: string
      update_date:
        description: 'Origin: ZZ'
        type: string
        format: date-time
      deleted:
        description: 'Origin: ZZ'
        type: boolean
        default: false
      type:
        description: 'Origin: ZZ'
        type: string
        enum:
          - passport
          - drivers_license
          - etc
      series:
        description: 'Origin: ZZ'
        type: string
      number:
        description: 'Origin: ZZ'
        type: string
      issue_date:
        description: 'Origin: ZZ'
        type: string
        format: date-time
      issued_by:
        description: 'Origin: ZZ'
        type: string
      validity:
        description: 'Origin: ZZ'
        type: string
        format: date-time
      check_status:
        type: string
        description: 'Origin: ZZ'
        enum:
          - passed
          - failed
      rejection_reason:
        description: 'Origin: ZZ'
        type: string
      link:
        description: 'Origin: ZZ'
        type: string
        example: 'http://data.zz.com/files/94a7g2j93j57927j4jjjj31928dfgewy752er935.pdf'
  ContactData:
    type: object
    properties:
      work_phone:
        description: 'Origin: ZZ'
        type: string
      mobile_phone:
        description: 'Origin: ZZ'
        type: string
      email:
        description: 'Origin: ZZ'
        type: string
      instant_messenger:
        description: 'Origin: ZZ'
        type: string
      skype:
        description: 'Origin: ZZ'
        type: string
  BankAccount:
    type: object
    properties:
      full_name:
        description: 'Origin: ZZ'
        type: string
      iban:
        description: 'Origin: ZZ'
        type: string
      bank_code:
        description: 'Origin: ZZ'
        type: string
  SignedDocument:
    type: object
    properties:
      id:
        description: 'Origin: ZZ'
        type: string
      update_date:
        description: 'Origin: ZZ'
        type: string
        format: date-time
      deleted:
        description: 'Origin: ZZ'
        type: boolean
        default: false
      type:
        description: 'Origin: 1C'
        type: string
        enum:
          - invoice
          - contract_application
          - acceptance_act
      sign_status:
        description: 'Origin: 1C'
        type: string
        enum:
          - signed
          - rejected
          - waiting
      link:
        description: 'Origin: 1C'
        type: string
        example: 'http://data.zz.com/files/94a7g2j93j57927j4jjjj31928dfgewy752er935.pdf'
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  zz_auth:
    type: oauth2
    authorizationUrl: 'https://api.zz.com/oauth/authorize'
    flow: implicit
