swagger: '2.0'
info: 
  title: 'UDK-ZZ API'
  description: 'The API is an HTTP interface for working with ZZ data. The base path for all API requests is https://api.zz.com/v1/. Use  https://sandbox-api.zz.com/v1/ - for testing purpozes.'
  version: 1.0.0
schemes:
  - https
  - http
host: 'api.zz.com'
basePath: '/v1'
consumes:
  - application/json
produces:
  - application/json
paths:
  /order/get:
    get:
      summary: 'Get an existing shipping order'
      description: 'Этот метод используется для получения данных заказа. Ответ возвращается в виде объекта ShippingOrder'
      operationId: getOrder
      parameters:
        - name: orderId
          in: query
          description: 'ID of shipping order to return'
          required: true
          type: string
      responses:
        200:
          description: 'successful operation'
          schema:
            $ref: '#/definitions/ShippingOrder'
        400:
          description: 'invalid ID supplied'
        404:
          description: 'shippingOrder not found'  
  /order/add:
    put:
      summary: 'Put new shipping order'
      description: 'Этот метод используется для передачи данных заказа.'
      operationId: addOrder
      parameters:
        - name: order
          in: body
          schema:
            $ref: '#/definitions/ShippingOrder'
      responses:
        200:
          description: 'successful operation'
        405:
          description: 'validation exception'
  /order/list:
    get:
      summary: 'Get shipping order list'
      description: 'Этот метод используется для получения массива заказов. Ответ возвращается в виде массива объектов ShippingOrder'
      operationId: getOrderList
      parameters:
        - name: updateDate
          in: query
          description: 'Date to filter orders'
          required: true
          type: string
          format: date-time
        - name: filter
          in: query
          description: 'Additional filter for orders'
          required: false
          type: string
          format: date-time
      responses:
        200:
          description: 'successful operation'
          schema:
            type: array
            items:
              $ref: '#/definitions/ShippingOrder'
        404:
          description: 'shippingOrders not found'  
definitions:
  ShippingOrder:
    type: object
    description: 'Заявка на доставку'
    properties:
      guid:
        type: string
        description: 'Origin: 1C. Уникальный идентификатор заявки'
      id:
        type: string
        description: 'Origin: ZZ'
      update_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      deleted:
        type: boolean
        default: false
        description: 'Origin: ZZ'
      date:
        type: string
        format: date-time
        description: 'Origin: ZZ. Дата регистрации заявки'
      currency:
        description: 'Origin: ZZ. Валюта документа'
        type: string
      rate_limit:
        type: number
        example: 1700.00
        description: 'Origin: 1C. Предельная ставка стоимости доставки'
      final_rate:
        type: number
        example: 1500.00
        description: 'Origin: ZZ. Окончательная ставка'
      execution_status:
        type: string
        description: 'Origin: ZZ. Статус заказа'
        enum:
          - order_created
          - order_canceled
          - tender
          - tender_confirmation
          - waiting_truck
          - waiting_loading
          - loading
          - on_the_way
          - waiting_unloading
          - unloading
          - delivered
      vehicle_type:
        type: string
        description: 'Origin: 1C. Типы транспортных средств'
        enum:
          - side_loading
          - back_loading
          - top_loading
          - etc
      order_items:
        type: array
        items:
          $ref: '#/definitions/OrderItem'
  OrderItem:
    type: object        
    description: 'Строка заявки на доставку'
    properties:
      guid:
        type: string
        description: 'Origin: 1C. Уникальный идентификатор строки заявки'
      id:
        type: string
        description: 'Origin: ZZ'
      update_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      deleted:
        type: boolean
        default: false
        description: 'Origin: ZZ'
      product_name:
        type: string
        description: 'Origin: 1C. Наименование товара'
      units:
        type: integer
        description: 'Origin: 1C. Единица измерения'
      multiplicity:
        type: integer
        description: 'Origin: 1C. Кратность количества товара'
      quantity:
        type: integer
        description: 'Origin: 1C. Количество товара'
      items:
        type: integer
        description: 'Origin: 1C. Количество мест товара'
      shipment_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      unload_date:
        type: string
        format: date-time
        description: 'Origin: ZZ'
      loading_address:
        type: string
        description: 'Origin: ZZ'
      unloading_address:
        type: string
        description: 'Origin: ZZ'
      comment:
        type: string
        description: 'Origin: ZZ'
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
  zz_auth:
    type: oauth2
    authorizationUrl: 'https://api.zz.com/oauth/authorize'
    flow: implicit
